# Creating NumPy ndarrays

There two ways of creating arrays.

1. We can create numpy arrays from other array-like object using numpy arrays, like regular python lists
2. We can use a variety of builtin numpy functions that quickly generates specific types of arrays

In [2]:
# Example of a 1d array.
import numpy as np
x = np.array([1,2,3,4,5])
print(x, type(x))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [4]:
x.dtype # to return the data type of elements in the np array
# numpy handles more datatypes that python

dtype('int32')

In [ ]:
x.shape # returns the tuple of n positive integers that specify the size of each dimension, n being the number of dimensions in the array.

(5,)

In [ ]:
## 1-D array
x = np.array([1, 2, 3])
x.ndim #returns the number of dimensions

1

In [30]:
## 2-D array
Y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(Y)
Y.ndim

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


2

In [ ]:
Y.shape # (row, col). Note the rows is the 1st dimension and the colums is the second dimension

(4, 3)

In [ ]:
x.size
Y.size # size retins the total number of elements in an ndimensional array.
# In reneral, we say an array with n dimensions has a rank n.

12

In [ ]:
# Strings
x = np.array(["Hello", "World"])
print(x)
print("shape:", x.shape)
print("size:", x.size)
print("class:", type(x))
print("dtype:", x.dtype) # stored unicode strings of k characters, where k is the len of the maximum elements in ndarray

['Hello' 'World']
shape: (2,)
size: 2
class: <class 'numpy.ndarray'>
dtype: <U5


In [31]:
# Mixing Integers and Strings
x = np.array([1, 2, "World"])
print(x)
print("shape:", x.shape)
print("size:", x.size)
print("class:", type(x))
print("dtype:", x.dtype) # even thought the python list had mixed datatypes, the array function created a numpy array with all elements of the same datatype U11 (UNICODE strings of 11 characters)
# unlike python lists, numpy arrays must contain elements of the same datatype.

['1' '2' 'World']
shape: (3,)
size: 3
class: <class 'numpy.ndarray'>
dtype: <U11


In [ ]:
# Mixing Integers and Floats
x = np.array([1, 2, 2.5])
print(x)
print("shape:", x.shape)
print("size:", x.size)
print("class:", type(x))
print("dtype:", x.dtype) # All elements will be assigned the float64 dtype in a process called upcasting

[1.  2.  2.5]
shape: (3,)
size: 3
class: <class 'numpy.ndarray'>
dtype: float64


In [33]:
# Specifying the dtype
x = np.array([1.8, 2.99, 7.5], dtype=np.int64)
print(x)
print("shape:", x.shape)
print("size:", x.size)
print("class:", type(x))
print("dtype:", x.dtype) # All elements will be assigned the specified dtype.

[1 2 7]
shape: (3,)
size: 3
class: <class 'numpy.ndarray'>
dtype: int64


In [ ]:
# Saving arrays to files and Loading them
x = np.array(["This", "is", "an", "interesting", "demo", 1,2,3])
np.save("myFristSave", x) # saves the array x into a file named myFirstSave.npy

In [36]:
y = np.load("myFristSave.npy")
print(y)
print("shape:", y.shape)
print("size:", y.size)
print("class:", type(y))
print("dtype:", y.dtype) # All elements will be 

['This' 'is' 'an' 'interesting' 'demo' '1' '2' '3']
shape: (8,)
size: 8
class: <class 'numpy.ndarray'>
dtype: <U11
