# Creating ndArrays with Inbuilt Functions

In [2]:
import numpy as np

## `np.zeros(shape)`

In [13]:
X = np.zeros((3,4))
print(X)
print(X.dtype)

print("\n")

X= np.zeros((3,4), dtype=int)
print(X)
print(X.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32


## `np.ones(shape)`

In [14]:
X2 = np.ones((3,4))
print(X2)
print(X2.dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64


## `np.full(shape, constant)`

In [15]:
X3 = np.full((4,5), 5)
print(X3)
print(X3.dtype)


X3 = np.full((4,5), 5, dtype=np.float64)
print(X3)
print(X3.dtype)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
int32
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]
float64


## `np.eye(size)`

In [16]:
X4 = np.eye(5, dtype=int) #dtype is optional
print(X4)
print(X4.dtype)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
int32


## `np.diag(list_or_tuple)`

In [22]:
X5 = np.diag((1,3,3,1))
print(X5, X5.dtype)


[[1 0 0 0]
 [0 3 0 0]
 [0 0 3 0]
 [0 0 0 1]] int32


## `np.arange(start, stop, step)`

In the output, `stop` is not inclusive. 

In [ ]:
X6 = np.arange(10) #with only one parameter specified
print(X6)

X6 = np.arange(-9, 9) #with two paramteters specified
print(X6)

X6 = np.arange(1, 5, 0.5) # with three parameters. But it is not advisable to use this one for decimal steps, use np.linspace
print(X6)

[0 1 2 3 4 5 6 7 8 9]
[-9 -8 -7 -6 -5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


## `np.linspace(start, stop, number_of_points_n)`

In the output, `stop` is inclusive

In [32]:
X7 = np.linspace(1, 5) # if n is not specified, it defaults to 50
print(X7)

X7 = np.linspace(1, 5, 10) # if n be specified, it returns n points including start and stop
print(X7)

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


For any start $a$ to stop $b$, to insert have $n$ points including $a$ and $b$, step size $\delta$ can be found using,

$$
\delta = \frac{b-a}{n-1}
$$

So we can see that to insert $10$ points including $1$ and $5$, the step size $\delta = \frac{5-1}{9} = \frac{4}{9} = 0.4444$

In [ ]:
# Hacking the endpoint
# we can remove the endpoint in the linspace output
X7 = np.linspace(1, 5, 10, endpoint=False)
print(X7, X7.dtype)

[1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6] float64


The step size in this case varries.

$$
\delta = \frac{b-a}{n}
$$

So for $X7$ above, $\delta = \frac{5-1}{10} = 0.4$

## Converting rank 1 arrays to rank 2 arrays: `np.rashape(1darray, shape)`

In [44]:
X8 = np.linspace(1, 20, 20, dtype=int)
print(X8)

print()

X8 = np.reshape(X8, (10, 2))
print(X8)

print()

X8 = np.linspace(1, 9, 9).reshape((3,3)) #reshape as a method
print(X8)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# Practical Use Case: Randomly Initializing the weights of a Neural Network

Let's create an array of a given shape $(m, n)$ with random floats between $0$ and $1$

## `np.random.random(size).reshape(shape)` or `np.random.random(shape)`

In [51]:
X9 = np.random.random(9).reshape((3,3))
print(X9)

print()

X9 = np.random.random((3,3))
print(X9)

[[0.53477594 0.39156165 0.59795276]
 [0.2187893  0.50016443 0.89560464]
 [0.93894222 0.69330922 0.43729359]]

[[0.66316351 0.78119803 0.73019733]
 [0.66865357 0.82340923 0.26744144]
 [0.55326825 0.03184088 0.19021536]]


## `np.random.randint(lower_bound, upper_bound, shape)`

In [ ]:
X10 = np.random.randint(4, 15, (3,2)) # lower bound inclusive, upper bound exclusive
print(X10)

[[ 8  4]
 [ 9  5]
 [12  5]]


# Random Numbers satisfying Certain Statistical Properties

## `np.random.normal(mean, std, shape)`

In [54]:
X11 = np.random.normal(0, 0.1, (1000, 1000))
print(X11)

[[-0.0384712  -0.1788607  -0.00358888 ... -0.09612637  0.16318274
  -0.07001409]
 [ 0.19388836 -0.14709334 -0.02988779 ...  0.0909294   0.00370989
  -0.14669617]
 [-0.03514991 -0.19218771 -0.05279152 ...  0.02790677  0.19204514
   0.06034965]
 ...
 [ 0.05562468  0.01304808 -0.00547991 ... -0.06319021  0.0223167
   0.05926964]
 [-0.0369523  -0.03037349 -0.17486125 ...  0.04722409  0.06191622
  -0.0016285 ]
 [-0.07209071  0.07872495 -0.06071073 ...  0.00584354 -0.05097514
   0.03903759]]


In [56]:
print("mean:", X11.mean())
print("std:", X11.std())
print("max:", X11.max())
print("min:", X11.min())
print("mean:", (X11 > 0).sum())
print("mean:", (X11 < 0).sum())

mean: -0.0001802363315031826
std: 0.10006839373448675
max: 0.46179090640232545
min: -0.5153853638485069
mean: 498988
mean: 501012


# Exercise

Create an ndarray

In [63]:
# Solutions
X = np.arange(2,34,2).reshape(4,4)
print(X)

print()
X = np.linspace(2,32,16).reshape(4,4)
print(X)

print()
X = np.random.uniform(1, 6, (4,4))
print(X)

print()
X = np.random.uniform(0, 1, 12).reshape(4,3)
print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]

[[ 2.  4.  6.  8.]
 [10. 12. 14. 16.]
 [18. 20. 22. 24.]
 [26. 28. 30. 32.]]

[[1.02781748 4.33512804 4.05626444 2.35781837]
 [4.68089874 5.04801738 4.22270343 3.20190565]
 [2.83313286 1.44465584 1.23003296 3.5355419 ]
 [4.02449153 1.0616054  3.12892199 1.94142399]]

[[0.80575079 0.67932217 0.39761083]
 [0.96214601 0.64726047 0.96346257]
 [0.9000355  0.04014169 0.12821446]
 [0.12262396 0.7505933  0.80646284]]
