# Accessing, Inserting and Deleting Elements from ndArrays

In [1]:
import numpy as np

Numpy nparrays are mutable, meaning we can change the elements in them after we have created them.

## Slicing an ndArray

This allows us to retrive any subset of the ndArray we want. This is applicable in separating data, e.g., when dividing the data into training, testing and cross-validation sets.

## Accessing Elements Through Indexing

In [2]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [4]:
print("1st elem:", x[0], "negative indices also returns: ", x[-5])
print("2nd elem:", x[1], "negative indices also returns: ",x[-4])
print("last elem:", x[-1], "negative indices also returns: ",x[4])

1st elem: 1 negative indices also returns:  1
2nd elem: 2 negative indices also returns:  2
last elem: 5 negative indices also returns:  5


## Modifying Elements in ndArray

In [7]:
x[3] = 20
print(x)

[ 1  2  3 20  5]


In [11]:
# For Rank 2 numpy arrays
X = np.arange(1, 10).reshape((3,3))
print(X)

print()

# Accessing some elements
print("elem at (0, 0) :", X[0, 0]) # remember this is zero indexing
print("elem at (0, 1) :", X[0, 1])
print("elem at (2, 2) :", X[2, 2])

print()

# Modifying elements
X[0,0] = 50
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

elem at (0, 0) : 1
elem at (0, 1) : 2
elem at (2, 2) : 9

[[50  2  3]
 [ 4  5  6]
 [ 7  8  9]]


## Deleting elements and the `axis` Keyword

When deleting, for a rank 1 array, the `axis` keyword is not required, for a rank 2 arrays, the `axis=0` selects rows and `axis=1` selects columns. 

In [13]:
# Deleting the first and last element of a rank 1 array

X = np.arange(4, 15)
print(X)

X = np.delete(X, [0, -1])
print(X)

[ 4  5  6  7  8  9 10 11 12 13 14]
[ 5  6  7  8  9 10 11 12 13]


In [19]:
# Deleting the first and last element of a rank 2 array

X = np.arange(1, 29).reshape(4,7)
print(X)

print()
X = np.delete(X, 0, axis=0) #delete the first row
print(X)

print()
X = np.delete(X, [1,3,5], axis=1) #delete columns 2, 4, and 6
print(X)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]]

[[ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]]

[[ 8 10 12 14]
 [15 17 19 21]
 [22 24 26 28]]


## Appending

In [24]:
x = np.array([1,2,3,4,5])
print(X)

print()
x = np.append(x, 6) # append single
print(x)

print()
x = np.append(x, [7,8]) # append multiple
print(x)

[1 2 3 4 5]

[1 2 3 4 5 6]

[1 2 3 4 5 6 7 8]


In [34]:
# Note the distictions
o = np.array([1,2,3]) #list
print(o.shape)
print(a.size)

a = np.array([[1,2,3]]) #row vector
print(a.shape)
print(a.size)

b = np.array([[1],[2],[3]])# column vector
print(b.shape)
print(a.size)

(3,)
3
(1, 3)
3
(3, 1)
3


In [ ]:
# Appening to 2darrays
x = np.arange(1,10).reshape(3,3)
print(x)

print()
x = np.append(x, [[10,11,12]], axis=0) #append to row. Shape should be a row vector
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [35]:
# Appending to columns
x = np.append(x, [[0],[0],[0],[0]], axis=1) # notice how we append to columns here. Append a column vector.
print(x)

[[ 1  2  3  0  0]
 [ 4  5  6  0  0]
 [ 7  8  9  0  0]
 [10 11 12  0  0]]


Note append always adds to the last row or last column What if we wanna add somewhere inbetween?

## Inserting elements into ndArrays

We need the array, index, element and axis.

## `np.insert(array, index, elem, axis)`

In [ ]:
# 1d example
x = np.arange(1,5)
print(x)

print()

x = np.insert(x, 2, 100, axis=0) #axis=0 is row, axis=1 is column, but axis=1 will cause error here.
print(x) # 100 inserted in index 2 or 3rd position

[1 2 3 4]

[  1   2 100   3   4]


In [51]:
# 2d example
x = np.arange(1, 10).reshape(3,3)
print(x)

print()
x = np.insert(x, 1, [0, 0, 0], axis=0) # insert zero rows in second row (index 1)
print(x) # insert3d

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [0 0 0]
 [4 5 6]
 [7 8 9]]


In [50]:
y = np.arange(1, 10).reshape(3,3)
print(y)

print()
y = np.insert(y, 1, [0,1,2], axis=1) # insert zero columns in 2nd column (index 1)
print(y) # insert3d

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 0 2 3]
 [4 1 5 6]
 [7 2 8 9]]


In [53]:
# Insert a column full of fives
x = np.array([[1,2,3],[4,5,6]])
print(x)

print()
x = np.insert(x, 1, 5, axis=1)
print(x)

[[1 2 3]
 [4 5 6]]

[[1 5 2 3]
 [4 5 5 6]]


## Stacking Numpy Arrays

To stack arrays, the shape of the arrays must match. We can stack vertically or horizontally.

In [56]:
x = np.array([1,2])
y = np.array([[3,4], [5,6]])

print("rank 1 array: ", x)
print("rank 2 array: \n", y)

rank 1 array:  [1 2]
rank 2 array: 
 [[3 4]
 [5 6]]


In [ ]:
# Vertical stacking
z = np.vstack((x, y)) # stack x ontop
print(z)

print()
z = np.vstack((y, x)) # stack x below
print(z)

[[1 2]
 [3 4]
 [5 6]]

[[3 4]
 [5 6]
 [1 2]]


In [59]:
# Horizontal stacking
z = np.hstack((y, x.reshape(2,1))) # convert x so that it has same rows as y to h-stack, stack to the right
print(z)

print()
z = np.hstack((x.reshape(2,1), y))
print(z)

[[3 4 1]
 [5 6 2]]

[[1 3 4]
 [2 5 6]]


## Exercise

In [69]:
A = np.full((2,2), 4)
print(A)

print()
B = np.array([[3,1], [-1, 3]])
print(B)

print("\nMatrix Sum") # Matrix sums
C = A + B
print(C)

print("\nMatrix Difference") # Matrix difference
C = A - B
print(C)

print("\nElement-wise Product") # Element-wise Product (Hadamard's)
C = A * B
print(C)

print("\nElement-wise Division") # Element-wise Division
C = A / B
print(C)

[[4 4]
 [4 4]]

[[ 3  1]
 [-1  3]]

Matrix Sum
[[7 5]
 [3 7]]

Matrix Difference
[[1 3]
 [5 1]]

Element-wise Product
[[12  4]
 [-4 12]]

Element-wise Division
[[ 1.33333333  4.        ]
 [-4.          1.33333333]]


Is there a way to do matrix products instead of Hadamard's product? If yes, find the product $C = AB$ and $D = BA$. For this two matrices $A$ and $B$, is the operation of prodduct commutative?

In [73]:
# Solution

C = A.dot(B)
print(C)

print()
D = B.dot(A)
print(D)

[[ 8 16]
 [ 8 16]]

[[16 16]
 [ 8  8]]


$AB \ne BA$, hence, matrix product is not always commutative, only and only when $A = B^{-1}$ or $B = A^{-1}$ or $A = 0$ or $B = 0$

In [76]:
A = np.zeros((2,2))
B = np.full((2,2), -1)

C = A.dot(B)
D = B.dot(A)

print(C, D, sep="\n\n")

[[0. 0.]
 [0. 0.]]

[[0. 0.]
 [0. 0.]]
