# Slicing nd Arrays

We do this to access a subset of the ndarray, unklike indexing that accesses individual elements.

In [1]:
import numpy as np

## Three Ways of Slicing

    1. ndarray[start:end]
    2. ndarray[start:]
    3. ndarray[:end]

Since numpy arrays are n-dimensional, we have to specify a slice for each dimension.

In [2]:
X = np.arange(1,21).reshape(4,5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [3]:
z = X[1:4, 2:5] #ndarray[a:b, c:d] must satisfy c - c == b - a
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [ ]:
# The same thing
z = X[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [5]:
# same columns, but different rows
z = X[:3, 2:]
print(z)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [ ]:
# Try to select all the elements in the third row
z = X[2:3, :]
print(z)

[[11 12 13 14 15]]


Rows are horizontal but they are selected vertical wise!

In [ ]:
# Select all the rows in column 2 (all elements )
z = X[:, 2] # ndarray[VERTICAL-WISE, HORIZONTAL-WISE]
print(z, z.shape) #returns a rank 1 numpy array  array

[ 3  8 13 18] (4,)


In [12]:
# Select all the elements in the thrid column and return it in a rank 2 array
z = X[:, 2].reshape(X.shape[0], 1)
print(z)
print(z.shape)

# or
print()
z = X[:, 2:3]
print(z)
print(z.shape)

[[ 3]
 [ 8]
 [13]
 [18]]
(4, 1)

[[ 3]
 [ 8]
 [13]
 [18]]
(4, 1)


When we slice into a new variable, the data isn't actually copied into a new variable.

In the example above, the slice of the array X is not copied into z, rather, X and z are just two different names for the same array. We say that slicing only creates a view of the original array. This is to the effect that if you make changes in z, you'll also be making the same changes in the background in X.

In [14]:
# Example
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [15]:
z = X[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [16]:
z[2,2] = 555
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


In [ ]:
print(X) # see that changing z also changed X.

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 555]]


But using the copy function or copy method, we can avoid this.

In [23]:
X = np.arange(1, 21).reshape(4, 5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [25]:
z = np.copy(X[1:, 2:]) #copy as a function
print(z)

print()
z = X[1:, 2:].copy() #copy as a method
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [26]:
# changing the last element in z, to see whether it affected X
z[2,2] = 555
print(z)

print()
print(X)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Create array as indices to make slices, select or change elements in another numpy array

In [28]:
X = np.arange(-19, 1).reshape(4,5)
print(X)

[[-19 -18 -17 -16 -15]
 [-14 -13 -12 -11 -10]
 [ -9  -8  -7  -6  -5]
 [ -4  -3  -2  -1   0]]


In [30]:
indices = np.array([1, 3])
print(indices, indices.shape)

[1 3] (2,)


In [32]:
# Using the indices to select some subsets of X
z = X[indices, :] #select the 2nd and 4th rows of X
print(z)

[[-14 -13 -12 -11 -10]
 [ -4  -3  -2  -1   0]]


In [ ]:
# Using the indices to select some subsets of X
z = X[:, indices] #select the 2nd and 4th columns of X
print(z)

[[-18 -16]
 [-13 -11]
 [ -8  -6]
 [ -3  -1]]


## Other Builtin Functions for Selection of Specific Elements from the numpy Array

### `np.diag(ndarray)`

In [34]:
print(X)

[[-19 -18 -17 -16 -15]
 [-14 -13 -12 -11 -10]
 [ -9  -8  -7  -6  -5]
 [ -4  -3  -2  -1   0]]


In [ ]:
z = np.diag(X) #default, k=0 
print(z)

[-19 -13  -7  -1]


In [35]:
z = np.diag(X, k=1) #elements above the main diagonal
print(z)

[-18 -12  -6   0]


In [ ]:
z = np.diag(X, -1) #elements below the main diagonal, k is optional
print(z)

[-14  -8  -2]


## `np.unique(ndarray)`

Helps us see unique elements in an ndarray.

In [39]:
X = np.array([[1,2,3], [5,2,8], [1,2,3]])
print(X)

[[1 2 3]
 [5 2 8]
 [1 2 3]]


In [41]:
z = np.unique(X)
print(z, z.shape)

[1 2 3 5 8] (5,)
