# Boolean Indexing, Set Operations, and Sorting

How do you handle situations where you don't know the indices of the elemets you want to select in an ndarray?

In [1]:
import numpy as np

Supposing we have a 10000 x 10000 array of random integers ranging from 1 to 15000, and we only want to select integers that are less than 20, boolean indexing can help us, by enabling us select elements using logical arguments instead of explicit indices.

In [3]:
X = np.arange(25).reshape(5,5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [4]:
# Select the elements greater than 10
z = X[X>10]
print(z, z.shape)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24] (14,)


In [5]:
# Select the elements less or equal to 7
z = X[X <= 7]
print(z) 

[0 1 2 3 4 5 6 7]


In [ ]:
# Select the elements greater than 10 and less than 17
z = X[(X > 10) & (X < 17)] #brackets are very important here.
print(z)

[11 12 13 14 15 16]


We can use boolean indexing to assign.

In [9]:
# all elements satisfying 10<el<17 should be reassigned to -1
X[(X > 10) & (X < 17)] = -1
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


## Set Operations

Useful when comparing 2 numpy arrays, for example, to find common elements.

In [14]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])

### Intersection, Difference, Union

In [15]:
# Intersection
print(np.intersect1d(x, y))

[2 4]


In [16]:
# Difference
print(np.setdiff1d(x,y))

[1 3 5]


In [17]:
# Union
print(np.union1d(x,y))

[1 2 3 4 5 6 7 8]


# Sorting Numpy Arrays

Using sort as a function, the original array is not change (sorting out of place). But when used as a method, sort affects the original array (sorting in place).

In [24]:
x = np.random.randint(1,11, size=(10,))
print(x)

[ 9  1  4  8  6  2  8  7  6 10]
